sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shreyp08/fibb-calc -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shreyp08/fibb-calc npm run test -- --coverage

after_success:
  - docker build -t shreyp08/multi-client ./client
  - docker build -t shreyp08/multi-nginx ./nginx
  - docker build -t shreyp08/multi-server ./server
  - docker build -t shreyp08/multi-worker ./worker
